### PR TITLE
Filter out debug entries from DV API log

### PR DESCRIPTION
**Pull request by kelvin-chappell**
The digital voucher API log has debug entries from the AWS SDK and from Netty.  They can obscure what's going on and are generally not very helpful.

This will filter them out.  AWS have no better suggestion for filtering them out.

### CODE REVIEW

**Review by mario-galic — APPROVED** [review]
Does this mean this files will have to be duplicated 20+ times?

**Comment by kelvin-chappell** [comment]
> Does this mean this files will have to be duplicated 20+ times?
Yes.  I suppose I might as well do them all in one go in this PR.

**Comment by mario-galic** [comment]
Maybe there is a better way...maybe source generation at the point of packaging.

**Comment by kelvin-chappell** [comment]
It's a one-off job and there are other longstanding debug entries leaking into the logs.  The Netty ones have been there for a while.  
All the handlers are already using logback: https://github.com/guardian/support-service-lambdas/blob/main/build.sbt#L253 so they should probably have explicit configuration anyway, which we'll need for our upcoming Json appender.

**Pull request merged**
