### PR TITLE
Adding RevenueEventItemInvoiceItem Query to zuora-datalake-export

### PR DESCRIPTION
**Pull request by wojtek-tg**
## Why
Data Delivery wants to test exporting largest possible dataset using the current methods to determine if we should extend the current process / evaluate some PaaS solution or back the possible direct S3 export.

## Does it work
We've checked the query in Zuora web UI (with limit) and it worked as expected. 

## Related PR:
https://github.com/guardian/ophan-data-lake/pull/4607

### CODE REVIEW

**Comment by wojtek-tg** [comment]
> Looks good to me, you just need to rebase with master.

Thanks, rebased.

**Comment by mario-galic** [comment]
If `RevenueEventItemInvoiceItem` is larger than `InvoiceItem` then full export will likely not complete within 8 hours at which point Zuora terminates the job. See https://github.com/guardian/support-service-lambdas/blob/master/handlers/zuora-datalake-export/README.md#how-to-extract-a-full-load-of-invoiceitem

**Comment by wojtek-tg** [comment]
I'm making a note that there are problems with Zuora data export and we opened a support case - that's why this isn't merged. I'll update this branch and notify you when I'll be merging this.

**Comment by mario-galic** [comment]
Should this be close?

**Comment by wojtek-tg** [comment]
@mario-galic is right we most probably don't need it now.

**Pull request closed without merging**
