### PR TITLE
Add a `check-formatting` pnpm script

### PR DESCRIPTION
**Pull request by tjmw**
## What does this change?

I've noticed that sometimes the TS code formatting in this repo drifts from the prettier config so I'd like to start checking formatting in CI, failing the build if there are files which aren't formatting correctly.

This adds a script `check-formatting` which can be run for the whole project:

`$ pnpm check-formatting`

or for a specific workspace:

`$ pnpm --filter alarms-handler check-formatting`

In #2230 I added a script to format the codebase, but on reflection I don't think this was very `pnpm`-ish. I think delegating to individual workspace `package.json`s is the way to go (so you can run for a specific workspace). I'll follow up with a PR to move over to this approach for formatting.

Then two more PRs:

* Fix the current formatting for the project
* Enforce formatting in CI.

## Accessibility

-   [ ] [Tested with screen reader](https://github.com/guardian/accessibility/blob/main/people-and-technology/03-visual.md#screen-reader)
-   [ ] [Navigable with keyboard](https://github.com/guardian/accessibility/blob/main/people-and-technology/02-physical.md#keyboard)
-   [ ] [Colour contrast passed](https://github.com/guardian/accessibility/blob/main/people-and-technology/03-visual.md#contrast)
-   [ ] [The change doesn't use only colour to convey meaning](https://github.com/guardian/accessibility/blob/main/people-and-technology/03-visual.md#use-of-colour)

### CODE REVIEW

**Review by rupertbates — APPROVED** [review]
Nice

**Review by jamesgorrie — APPROVED** [review]
Great - could we add a `fix-formatting`?

**Comment by tjmw** [comment]
> Great - could we add a `fix-formatting`?

Yep that's coming up! There actually is already a `format` command in the root package.json, but it's not very pnpm-y. I'm going to migrate it so that it can be run per workspace if needed, to mirror `check-formatting`.

**Comment by jamesgorrie** [comment]
> > Great - could we add a `fix-formatting`?
> 
> Yep that's coming up! There actually is already a `format` command in the root package.json, but it's not very pnpm-y. I'm going to migrate it so that it can be run per workspace if needed, to mirror `check-formatting`.

@tjmw - what's the benefit of having it per package vs moving this command to the root given formatting is a repo-wide concern?

**Comment by jamesgorrie** [comment]
> and gives more flexibility

I suppose my question is do we get more benefit from being flexible or standardising. When someone starts a new package, should they not have to think about how they want to implement this and just get it for free?

**Comment by tjmw** [comment]
> > and gives more flexibility
> 
> I suppose my question is do we get more benefit from being flexible or standardising. When someone starts a new package, should they not have to think about how they want to implement this and just get it for free?

👍 Yeah it's a good question. Right now you get a sensible default for free from the `new-lambda` script, so you don't have to think about it, unless you want to do something different for some reason.

**Comment by johnduffell** [comment]
I think we should enforce things everywhere as long as they can also be set up to format compliantly in the IDEs
A more general point - At the moment we have individual GHA builds for each lambda, so ideally we could only check the relevant code for each lambda in its own build (at the moment, all the builds build all the TS code, so if there's an issue anywhere, they all fail, which is not ideal.)

**Comment by tjmw** [comment]
> A more general point - At the moment we have individual GHA builds for each lambda, so ideally we could only check the relevant code for each lambda in its own build (at the moment, all the builds build all the TS code, so if there's an issue anywhere, they all fail, which is not ideal.)

Ha yes I've just realised this today and am experimenting with some alternatives.

**Comment by tjmw** [comment]
@johnduffell I've attempted to improve things here: #2341

**Pull request merged**
